 version: 2.1
 jobs:
   validate:
     docker:
       - image: 'cimg/node:14.14.0'
     steps:
       - run: sudo npm install @openapitools/openapi-generator-cli -g
       - run: openapi-generator version
       - checkout
       - run: find endpoints -name \*.yaml -a ! -name _\*.yaml | xargs -0 -n1 -P1 openapi-generator validate -i
 workflows:
   version: 2
   validation:
     jobs:
       - validate
