 version: 2
 jobs:
   validate:
     docker:
       - image: circleci/node
     steps:
       - run: sudo apt update
       - run: sudo npm install @openapitools/openapi-generator-cli -g
       - run: sudo apt-get install openjdk-8-jre-headless
       - run: openapi-generator version
       - checkout
       - run: find endpoints -name \*.yaml -a ! -name _\*.yaml | xargs -0 -n1 -P1 openapi-generator validate -i
 workflows:
   version: 2
   validation:
     jobs:
       - validate
