openapi: '3.0.2'
info:
  title: Impression Subscription
  version: '6.0.0'
servers:
  - url: https://api.server.test/v1
paths: {}
components:
  schemas:
    ImpressionSubscribe:
      properties:
        name:
          description: any meaningful name for this subscription
          type: string
        frequency:
          description: frequency by which notifications are expected
          type: string
          enum:
          - Hourly
          - Daily
          - Weekly
          - Monthly
        span:
          description: describe the impression span expected per each delivery
          type: object
          properties:
            num:
              description: combined with spanUnit this integer is used to express the coverage of the impression content, i.e. 5 days
              type: integer
            spanUnit:
              type: string
              enum:
              - Hours
              - Days
              - Weeks
              - Months
        referenceIds:
          description: this array can be used to limit the impression to given set of orders
          type: array
          items:
            $ref: "./commonSchemas.yaml#/components/schemas/referenceId"
        callbackUrl:
          description: URL to which notifications will be delivered
          type: string
          format: uri
          example: https://buyer.server.com/send/callback
      required:
        - name
        - callbackUrl