openapi: 3.0.0
info:
  version: 5.1.0
  title: Invoice Schema
  description: Invoice Schema
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: TIP Initiative
    email: tipinitiative@frontrowadvisory.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths: {}
components:
  schemas:
    SellerInvoices:
      description: Invoice schema
      properties:
        transactionHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/TransactionHeader'
        referenceIds:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/ReferenceId'
        invoiceDate:
          description: Date in which the original invoice was generated
          type: string
          format: date
        invoiceRevisionDate:
          description: Required for Invoice Revision – date in which the invoice revision was generated
          type: string
          format: date
        billingOption:
          $ref: 'commonSchemas.yaml#/components/schemas/BillingOption'
        dueDate:
          description: Date in which payment is due
          type: string
          format: date
        dateWindow:
          $ref: 'commonSchemas.yaml#/components/schemas/DateWindow'
        businessType:
          description: Seller-defined type of business
          type: string
        buyer:
          $ref: 'commonSchemas.yaml#/components/schemas/Buyer'
        localNational:
          description: Local or National marketplace
          type: string
          enum:
            - Local
            - National
        advertiser:
          $ref: 'commonSchemas.yaml#/components/schemas/Advertiser'
        contacts:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/Contact'
        revenueType:
          description: The agreed upon type of payment
          type: string
          enum:
            - Cash
            - Barter
            - Trade
        grossAmount:
          description: Totals gross amount for the invoice
          type: number
          format: float
        commission:
          description: Buyer commission amount for the invoice
          type: number
          format: float
        salesTax:
          description: Total sales tax applied to any elements on the invoice depending on state of invoice
            origin
          type: number
          format: float
        netAmount:
          description: >-
            Total net amount for all units within the invoice start and end date (gross amount– commission
            amount + sales tax)
          type: number
          format: float
        currency:
          $ref: 'commonSchemas.yaml#/components/schemas/Currency'
        remittanceInfo:
          $ref: 'commonSchemas.yaml#/components/schemas/RemittanceInfo'
        externalComment:
          description: Free form text to accommodate transaction comments and/or activities outside the
            TIP flow
          type: string
        lineDetails:
          type: array
          items:
            $ref: '#/components/schemas/LineDetail'
      required:
        - transactionHeader
        - referenceIds
        - invoiceDate
        - dateWindow
        - buyer
        - advertiser
        - revenueType
        - grossAmount
        - commission
        - netAmount
        - remittanceInfo
        - lineDetails
    LineDetail:
      description: Line Detail Information
      properties:
        buyLineIdReference:
          description: Seller's Line information
          type: string
        buyLineIdName:
          description: Buyer's line information associated to seller's line
          type: string
        type:
          description: >-
            Indicates the type of information in the line detail information. For example for unit type
            lines this would refer to linear spots vs impressions would refer to an audience buy
          type: string
          enum:
            - Units
            - Impressions
            - Flat Rate
        brand:
          $ref: 'commonSchemas.yaml#/components/schemas/Brand'
        product:
          $ref: 'commonSchemas.yaml#/components/schemas/Product'
        salesElement:
          $ref: 'commonSchemas.yaml#/components/schemas/SalesElementHeader'
        timePeriod:
          $ref: 'commonSchemas.yaml#/components/schemas/TimePeriod'
        length:
          description: Length of commercial unit
          type: integer
        cpeCode:
          $ref: 'commonSchemas.yaml#/components/schemas/CpeCode'
        billableRevenue:
          description: Indicates if the invoice rate being provide are booked or actual (earned) rates
          type: string
          enum:
            - Booked
            - Actuals
        rate:
          type: number
          format: float
          minimum: 0
        inventoryType:
          $ref: 'commonSchemas.yaml#/components/schemas/InventoryType'
        audiencePricingMetrics:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/AudiencePricingMetric'
        totalUnits:
          description: Total number of raw (unequivalized) linear units within the line's start and end
            date
          type: integer
          format: int64
          minimum: 0
        unitDetails:
          type: array
          items:
            $ref: '#/components/schemas/UnitDetail'
      required:
        - buyLineIdReference
        - type
        - product
        - salesElement
        - length
    UnitDetail:
      description: Unit details information (required for "unit" type only)
      properties:
        unitId:
          description: Seller generated unique number - Required when unit type is equal to units
          type: string
        adId:
          type: string
        dateTime:
          $ref: 'commonSchemas.yaml#/components/schemas/DateTime'
        podPosition:
          $ref: 'commonSchemas.yaml#/components/schemas/InventoryPosition'
        linkType:
          $ref: 'commonSchemas.yaml#/components/schemas/LinkType'
        preempt:
          description: True/False
          type: boolean
        makegood:
          description: True/False
          type: boolean
        adu:
          description: True/False
          type: boolean
        bonus:
          description: True/False
          type: boolean
        rate:
          description: the billed rate associated to the unit
          type: number
          format: float
        credit:
          description: True/False
          type: boolean
        adjustmentReason:
          description: >-
            Only valid on invoice revisions – reason for change of unit, example data: rate adjustment,
            incorrect copy
          type: string
        comment:
          description: Overall comment for the unit
          type: string
        childUnits:
          type: array
          items:
            $ref: '#/components/schemas/ChildUnitDetail'
      required:
        - unitId
    ChildUnitDetail:
      description: >-
        Child unit details for parent unit to support Mirror, Audience Network, Diginet or other forms
        of "child" units
      properties:
        unitId:
          description: Unique identifier for "child" unit
          type: string
        mediaOutlet:
          $ref: 'commonSchemas.yaml#/components/schemas/MediaOutlet'
        rate:
          description: Unit rate associated to the "child" unit
          type: number
          format: float
        adId:
          description: Ad-ID assigned to "child" unit
          type: string
        preempt:
          type: boolean
        makegood:
          type: boolean
        adu:
          type: boolean
        credit:
          type: boolean
        adjustmentReason:
          description: >-
            Only valid on invoice revisions – reason for change of unit, example data: rate adjustment,
            incorrect copy
          type: string
        dateTime:
          $ref: 'commonSchemas.yaml#/components/schemas/DateTime'
